import accordion, { accordion2 } from "./modules/accordion";
import burger from "./modules/burger";
import calc from "./modules/calc";
import checkTextInputs from "./modules/checkTextInputs";
import filter from "./modules/filter";
import forms from "./modules/forms";
import mask from "./modules/mask";
import modals from "./modules/modals";
import pictureSize from "./modules/pictureSize";
import scrolling, { scroll2 } from "./modules/scrolling";
import showMoreStyles from "./modules/showMoreStyles";
import showMoreStylesServer from "./modules/showMoreStylesServer";
import sliders from "./modules/sliders";

window.addEventListener("DOMContentLoaded", () => {
	"use strict";
	modals();
	sliders(".feedback-slider-item", "", ".main-prev-btn", ".main-next-btn");
	sliders(".main-slider-item", "vertical");
	forms();
	mask("[name='phone']");
	checkTextInputs("[name='name']");
	checkTextInputs("[name='message']");
	// showMoreStyles(".button-styles", ".styles-2");
	showMoreStylesServer(".button-styles", "#styles .row");
	calc("#size", "#material", "#options", ".promocode", ".calc-price");
	filter();
	pictureSize(".sizes-block");
	// accordion(".accordion-heading", ".accordion-block");
	accordion2(".accordion-heading");
	burger(".burger-menu", ".burger");
	// scrolling();
	scroll2();
});
